name: sentiment_env
channels:
  - pytorch
  - huggingface
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip=23.0
  - pytorch=2.0.1
  - numpy=1.24.3
  - pip:
    - transformers==4.36.2
    - streamlit==1.29.0
    - python-dotenv==1.0.0 